# Generated by Django 6.0 on 2025-12-19 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=100)),
                ('brand', models.CharField(choices=[('Toyota', 'Toyota'), ('Ford', 'Ford'), ('BMW', 'BMW'), ('Audi', 'Audi'), ('Honda', 'Honda'), ('Chevrolet', 'Chevrolet'), ('Nissan', 'Nissan'), ('Volkswagen', 'Volkswagen'), ('Hyundai', 'Hyundai'), ('Kia', 'Kia'), ('Mazda', 'Mazda'), ('Subaru', 'Subaru'), ('Dodge', 'Dodge'), ('Jeep', 'Jeep'), ('Lexus', 'Lexus'), ('Mercedes-Benz', 'Mercedes-Benz'), ('Cadillac', 'Cadillac'), ('Acura', 'Acura'), ('Infiniti', 'Infiniti'), ('Tesla', 'Tesla')], max_length=50)),
                ('factory_year', models.PositiveIntegerField()),
                ('model_year', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=50)),
                ('mileage', models.PositiveIntegerField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_available', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='car_images/')),
            ],
        ),
    ]
