# Generated by Django 6.0 on 2025-12-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_brand_alter_car_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='highlighted',
            field=models.BooleanField(default=False, verbose_name='Destaque'),
        ),
    ]
