# Generated by Django 6.0 on 2025-12-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_car_highlighted'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='Zero KM'),
        ),
    ]
