# Generated by Django 6.0 on 2025-12-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_car_is_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.CharField(default='Manual', max_length=50, verbose_name='Transmissão'),
        ),
    ]
