# Generated by Django 6.0 on 2026-01-11 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_car_transmission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Marca', 'verbose_name_plural': 'Marcas'},
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Carro', 'verbose_name_plural': 'Carros'},
        ),
    ]
