# Generated by Django 6.0.1 on 2026-08-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0007_alter_brand_options_alter_car_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="mileage",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="Quilometragem"
            ),
        ),
        migrations.AddIndex(
            model_name="car",
            index=models.Index(fields=["is_available"], name="idx_car_available"),
        ),
        migrations.AddIndex(
            model_name="car",
            index=models.Index(fields=["brand"], name="idx_car_brand"),
        ),
        migrations.AddIndex(
            model_name="car",
            index=models.Index(fields=["-price"], name="idx_car_price_desc"),
        ),
        migrations.AddIndex(
            model_name="car",
            index=models.Index(fields=["-model_year"], name="idx_car_year_desc"),
        ),
    ]
